INSERT INTO chapters (id, display_name, states, created_at) VALUES
  ('canada',         'Canada Chapter',         ARRAY['Canada'],                          now()),
  ('carolinas',      'Carolinas Chapter',       ARRAY['NC', 'SC'],                        now()),
  ('california',     'California Chapter',      ARRAY['CA'],                              now()),
  ('chicago',        'Chicago Chapter',         ARRAY['IL'],                              now()),
  ('florida',        'Florida Chapter',         ARRAY['FL'],                              now()),
  ('georgia',        'Georgia Chapter',         ARRAY['GA'],                              now()),
  ('michigan',       'Michigan Chapter',        ARRAY['MI'],                              now()),
  ('minnesota',      'Minnesota Chapter',       ARRAY['MN'],                              now()),
  ('mt-hood',        'Mt Hood Chapter',         ARRAY['OR'],                              now()),
  ('new-england',    'New England Chapter',     ARRAY['MA', 'CT', 'RI', 'ME', 'NH', 'VT'], now()),
  ('ny-nj-pa',       'NY-NJ-PA Chapter',        ARRAY['NY', 'NJ', 'PA'],                  now()),
  ('ohio',           'Ohio Chapter',            ARRAY['OH'],                              now()),
  ('ozark',          'Ozark Chapter',           ARRAY['KS', 'KY', 'IA', 'MO'],            now()),
  ('rocky-mountain', 'Rocky Mountain Chapter',  ARRAY['CO', 'MT', 'WY', 'ND', 'SD'],      now()),
  ('seattle',        'Seattle Chapter',         ARRAY['WA'],                              now()),
  ('southern',       'Southern Chapter',        ARRAY['TN', 'LA', 'MS', 'AL', 'KY'],      now()),
  ('southwest',      'Southwest Chapter',       ARRAY['TX', 'AR', 'NM', 'OK'],            now()),
  ('washington-dc',  'Washington DC Chapter',   ARRAY['MD', 'DC', 'VA', 'WV', 'DE'],      now())
ON CONFLICT (id) DO NOTHING;